const mongoose=require('mongoose');

const examSchema=new mongoose.Schema({
    title:{
        type:String,
        required:true,
        trim:true
    },
    description:{
        type:String,
        trim:true,
        default:''
    },
    durationMinutes:{
        type:Number,
        required:true,
        min:1
    },
    startsAt:{
        type:Date
    },
    endsAt:{
        type:Date
    },
    createdBy:{
        type:mongoose.Schema.Types.ObjectId,
        ref:'User',
        required:true
    },
    visibility:{
        type:String,
        enum:['public','organizations','custom','mixed'],
        default:'public'
    },
    organizationTargets:{
        type:[{
            type:mongoose.Schema.Types.ObjectId,
            ref:'Organization'
        }],
        default:[]
    },
    invitedStudentEmails:{
        type:[String],
        default:[]
    },
    questions:[{
        type:mongoose.Schema.Types.ObjectId,
        ref:'Question'
    }]
},{
    timestamps:true
});

module.exports=mongoose.model('Exam',examSchema);
